### ISSUE TITLE
Agreeing to a gig

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#15]
As a soloist, when I confirm to a gig through an email by clicking "yes" I am taken to the last bemusical page displayed on my computer, even after I close all the windows. 
![screen shot 2017-11-01 at 1 49 34 pm](https://user-images.githubusercontent.com/31675533/32297241-c4b19d10-bf0b-11e7-86c0-b45674e17113.png)

**Comment by DavelBM** [comment]
@baranskiy not 100% it is a bug. it rather seems to be that you were was signed into a new account that wasn't verified yet while also clicking a link on your email from another existing/verified account to accept to a gig... this shouldn't happen to regular users as they wouldn't create multiple accounts under the same email address but we should check into options like displaying a message: "you are signed into a different account"
