### ISSUE TITLE
Adding a member

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#16]
This is a little confusing. I think the main member of the ensemble should be able to add all the members without asking their permissions.

The permission should be asked if something decides to form a completely new ensemble made up of musicians that have connected through our platform. 

![screen shot 2017-11-01 at 2 00 03 pm](https://user-images.githubusercontent.com/31675533/32297706-3d35ab72-bf0d-11e7-813e-176d0783cba2.png)

**Comment by DavelBM** [comment]
we need to verify that they actually belong to that particular ensemble. what if the main member adds someone that's not part of his/her ensemble by accident?

**Comment by ghost** [comment]
I think we need to compare the probability of that ever happening against how important for us to make signing up as easy as possible.
