### ISSUE TITLE
Profile pic upload taking over

### ISSUE THREAD

**Issue by DavelBM** [DavelBM/test.bemusical.us#23]
when first uploading a profile pic to a profile the picture takes over the entire page:

<img width="1038" alt="screen shot 2017-11-01 at 18 29 53" src="https://user-images.githubusercontent.com/31047486/32305443-d0833fdc-bf32-11e7-9318-8b3226f3d6a7.png">

**Comment by cjairm** [comment]
check dimentions, and check uploading bar
CHECKED @DavelBM
