### ISSUE TITLE
Availability or travel distance immediate results

### ISSUE THREAD

**Issue by DavelBM** [DavelBM/test.bemusical.us#31]
We should be able to tell the client that the musician is not available on that date or that they don't travel to that location, either **before submitting their request** or **we let them submit it and instead of showing error, we through them at a results page with musicians that would fit their query.**

<img width="1440" alt="screen shot 2017-11-04 at 15 55 09" src="https://user-images.githubusercontent.com/31047486/32410216-9ffcac16-c178-11e7-8f47-360f7f48dabd.png">

**Comment by cjairm** [comment]
change 1 to 7 mi (miles around) (como minimo)
show errors in query page

**Comment by cjairm** [comment]
CHECKED @DavelBM
