### ISSUE TITLE
Bio Vs. About

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#34]
The difference between bio and about is confusing. Specifically, "bio" has a small field to paste in and "about" has a big one. Can we help musicians differentiate it? I think it should be the other way around. "About" should be short and maybe have a character count up to 50 characters. We can also have a message that prompts them to be brief: "A funky drummer from SF." So then the bio can be for a more descriptive info. 
![screen shot 2017-11-07 at 11 54 17 am](https://user-images.githubusercontent.com/31675533/32514791-eefd9352-c3b2-11e7-870d-5a24920ddfb9.png)

**Comment by DavelBM** [comment]
@baranskiy Agreed.

- [ ] We need to change Labels and input length.
