### ISSUE TITLE
SoundCloud not accepted "real bug"

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#35]
Can't upload SoundCloud even though it is listed as an acceptable format

https://drive.google.com/open?id=1a-V2LOm6gLQCAAs5ROO8YLzBjgVLwPmI

**Comment by DavelBM** [comment]
@baranskiy I cant access your video, but I'm assuming you tried entering the url...? If so, that's not possible, you can only enter the embed code they provide.

**Comment by ghost** [comment]
Then it has to be mentioned to dumb musicians like me that can’t tell the difference 

Roman

**Comment by ghost** [comment]
Embedded code doesn't work either for me.

**Comment by ghost** [comment]
Never mind. Finally cake through. But we will need better directions for musicians on how to add SoundCLoud
