### ISSUE TITLE
Searching for musicians

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#39]
Not sure if I am missing something but the search options doesn't work for me 

Check the video

https://drive.google.com/open?id=1xVSq9VH0XIf9Ylc04-ZrMsdREE3EKWVp

**Comment by DavelBM** [comment]
@cjairmjuarez Filters are not working...

**Comment by cjairmjuarez** [comment]
@baranskiy @DavelBM I can't see the video

**Comment by cjairm** [comment]
@DavelBM @baranskiy Checked
