### ISSUE TITLE
Phone Number

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#4]
Can't submit a phone number.
![screen shot 2017-11-01 at 12 13 34 pm](https://user-images.githubusercontent.com/31675533/32292792-6d411b44-befe-11e7-988a-c3ac387654c7.png)

**Comment by DavelBM** [comment]
@baranskiy did you enter it manually or was it a suggestion by your browser?

**Comment by ghost** [comment]
Entered manually 

Roman

**Comment by DavelBM** [comment]
@baranskiy can you try again? because it is working for me...

Check:

https://drive.google.com/file/d/0BzgsJWXLmw3AWllZeHJjQTJFeEU/view?usp=sharing

**Comment by DavelBM** [comment]
- [x] **We need to mask/format the number, so the user cant format it in any other way.**

**Comment by DavelBM** [comment]
@cjairmjuarez 

$(":input").inputmask();

$("#phone").inputmask({"mask": "(999) 999-9999"});

**Comment by ghost** [comment]
I was able to do it when I entered only numbers. Maybe the message should be "enter only numbers"?

**Comment by DavelBM** [comment]
@baranskiy it doesn't allow you now to enter anything other than numbers.
