### ISSUE TITLE
Unable to join an ensemble.

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#41]
So I requested myself (romanbaranskiy@gmail.com) to join bambino group. And after I have submitted my info I got pressed submit
![screen shot 2017-11-07 at 4 57 45 pm](https://user-images.githubusercontent.com/31675533/32526208-fd583b26-c3dc-11e7-9595-3017e8c10ba2.png)
 and got this screen:

**Comment by cjairm** [comment]
Can I see the button or the screen before this? 

Because I also request myself to join an ensemble and everything works fine  

@baranskiy @DavelBM

**Comment by ghost** [comment]
Link from email: https://test.bemusical.us/ensemble/invitation/tiWomugqKNqLeTurn85M5rbMshGw5iDZsxowACB2I76Ix29pVX1510102290

Link from ensemble's page: 
https://test.bemusical.us/ensemble/dashboard

Video of me doing it: 
https://drive.google.com/open?id=1zjtJy9DZHsObAZbIQhCmX1lY9tnd_UsG

**Comment by DavelBM** [comment]
@cjairmjuarez Check those links

**Comment by cjairm** [comment]
@baranskiy @DavelBM Checked
