### ISSUE TITLE
When updating calendar, it sends me back to current month

### ISSUE THREAD

**Issue by DavelBM** [DavelBM/test.bemusical.us#45]
If I'm working on blocking days in the future, it is very annoying to have to go back and look for the month I was working on.

https://drive.google.com/file/d/1GpP4O9NFJ_iU3AEKdZR1hTtCKmm9jwRy/view?usp=sharing

**Comment by DavelBM** [comment]
@cjairmjuarez is this on our back end or front end?

**Comment by cjairm** [comment]
@DavelBM  Actually, I think they are both. The front end developer needs to "change in real time" the calendar, and I couldn't
