### ISSUE TITLE
Clients can't pick a time after 9am

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#47]
https://drive.google.com/open?id=1BlCIBRnfQhnlwEr9yrSxXiBz-_H9rpKN

**Comment by DavelBM** [comment]
@baranskiy Did you block off that musician's availability? most likely yes otherwise it'd show the times that profile is available. Smarty pants!

**Comment by ghost** [comment]
That was before I picked a musician. It was a general request

Roman
