### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#5]
It doesn't find any styles. So I can't enter classical or Jazz as my playing style. 
![screen shot 2017-11-01 at 12 23 25 pm](https://user-images.githubusercontent.com/31675533/32293213-b3c22e36-beff-11e7-9c1e-7873b7744c5c.png)

**Comment by DavelBM** [comment]
@baranskiy  admins we have to provide the styles that are available to users. Check your admin account.
