### ISSUE TITLE
the email to reset password has wrong links (localhost..)

### ISSUE THREAD

**Issue by DavelBM** [DavelBM/test.bemusical.us#68]
Nice template, but we gotta update those links:

--_=_swift_v4_1511403091_7464bb7827ef6eb05b031b7fee3ec37c_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

[BeMusical](http://localhost)

# Hello!

You are receiving this ema=
il because we received a password reset request for your account.

Rese=
t Password: http://localhost/password/reset/e8c84ae42370c4133e2feba870a08d8=
a3321b831e4757bca77dec33aaf88d201

If you did not request a password re=
set, no further action is required.

Regards,BeMusical

If you=
=E2=80=99re having trouble clicking the "Reset Password" button, copy and p=
aste the URL below
into your web browser: [http://localhost/password/rese=
t/e8c84ae42370c4133e2feba870a08d8a3321b831e4757bca77dec33aaf88d201](http://=
localhost/password/reset/e8c84ae42370c4133e2feba870a08d8a3321b831e4757bca77=
dec33aaf88d201)

=C2=A9 2017 BeMusical. All rights reserved.

**Comment by cjairm** [comment]
checked @DavelBM @baranskiy
