### ISSUE TITLE
Broken login redirect

### ISSUE THREAD

**Issue by DavelBM** [DavelBM/test.bemusical.us#69]
- [x] when logging in, it doesn't redirect to the dashboard page

- [x] then if you try to reset the password, the DB cannot find the account

https://drive.google.com/file/d/1-obNAakFAg0wLVe_t8tPesJZe5XImJPO/view?usp=sharing

**Comment by cjairm** [comment]
Okay... the first one is redirecting correctly, we are using a function call "intented()". For example, if we type in the url bar https://www.test.bemusical.us/events/info, and you are not logged... this redirects to login page, so when you login it redirects automatically to the "intented() url". We can take out that function in the login if you want.

The second one, you were in the wrong "searcher", you were in admin's password reset

@DavelBM @baranskiy
