### ISSUE TITLE
Can't designate a gig as an Admin

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#78]
After receiving a general request as an Admin I have tried giving it to a musician but got an error message. On the video, I didn't check to make sure that the dates align. But I did check it after and got the same error. Please check the video: 

https://drive.google.com/open?id=1bHJSNgWZ_dkfIB16ywZN7Ajh6fureoTr

**Comment by cjairm** [comment]
Has to be tested @baranskiy @DavelBM

**Comment by ghost** [comment]
@DavelBM @cjairmjuarez Still buggy. Can't get passes the error message

**Comment by cjairm** [comment]
Already works @baranskiy
