### ISSUE TITLE
Can't verify email of a new user

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#79]
Check the video: https://drive.google.com/open?id=1EuiUgnVBs3eui1Yuu0ccj5dUcZeaXZuK

**Comment by DavelBM** [comment]
Mira @cjairmjuarez

**Comment by cjairm** [comment]
Checked @baranskiy @DavelBM

**Comment by ghost** [comment]
@DavelBM @cjairmjuarez 

Cleared history, cache, and cookie. Still buggy.

**Comment by cjairm** [comment]
Checked, and tested @baranskiy
