### ISSUE TITLE
Where are the FaceBook and LinkdIn?

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#80]
I don't see "register with FaceBook" or "register with LinkedIn" buttons. They are available only for signing in to already preexisting accounts.

**Comment by DavelBM** [comment]
@cjairmjuarez Tenemos que poner botones para registrarse con Fb y LinkedIn en el "[Register](https://test.bemusical.us/register)" view.

**Comment by cjairm** [comment]
checked @baranskiy @DavelBM

**Comment by ghost** [comment]
@DavelBM @cjairmjuarez 

you fixed it for ensembles but it's still absent for soloists

**Comment by cjairm** [comment]
Checked @baranskiy
