### ISSUE TITLE
Where is the schedule?

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#90]
Hey, I just created two new complete profiles but the ability to update the schedule has disappeared. Where should I look for it?

**Comment by cjairm** [comment]
Okay.. I went to the database to check, and we we have the same issue in #84 

> @baranskiy This is because as musician must to "ask to make my profile visible", and to fix this problem you need to do this.
> 
> 1.-Go to admin dashboard, and hide his/her profile from public
> 2.-Go to musician dashboard, and "ask to make my profile visible"
> 3.-Return to admin dashboard, and make it visible.
> 
> And you will have the others actions that you have not now, such as, percent bar, payments, payouts, calendar
