### ISSUE TITLE
Gig requests show unavailable profiles. 

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#91]
Soloist 2 is unavailable on Fridays but is still shown in the main request page: 

![screen shot 2017-12-08 at 4 37 53 pm](https://user-images.githubusercontent.com/31675533/33790595-5402344c-dc36-11e7-8edb-80fe452227b0.png)

**Comment by cjairm** [comment]
@baranskiy  checked :) and improved. Sorry for the delay
