### ISSUE TITLE
 3530111333300000 JCB Doesn't work

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#92]
I've noticed that all the cards that don't ask for zip code come back as error, including this one

**Comment by cjairm** [comment]
@baranskiy Hey!

Can I see a screenshot? I already tested the card, and everything went good.

**Comment by ghost** [comment]
@cjairmjuarez I can't submit any new requests because the time slot doesn't work again: 

https://drive.google.com/open?id=1BxDqBfVG5lEjPYppVYKVCBDtsFAU8qKz

**Comment by cjairm** [comment]
@baranskiy  I never thought in that case, but I already fix it. Checked!
