### ISSUE TITLE
Preguntar solo una ves que son...

### ISSUE THREAD

**Issue by DavelBM** [DavelBM/test.bemusical.us#96]
Cuando me registro con mi email, me pregunta solo una ves si soy soloist o ensemble pero si lo hago con facebook o LinkedIn me vuelve a preguntar, que podemos hacer ahi para que solo nos pregunte al principio?

<img width="1212" alt="screen shot 2017-12-24 at 17 34 59" src="https://user-images.githubusercontent.com/31047486/34330401-fe5961e4-e8d0-11e7-96cc-e81400c494ab.png">

**Comment by cjairm** [comment]
@DavelBM  checked!
