### ISSUE TITLE
Deberiamos poder guardar datos del perfil sin necesidad que todo este completo

### ISSUE THREAD

**Issue by DavelBM** [DavelBM/test.bemusical.us#97]
<img width="1440" alt="screen shot 2017-12-24 at 18 16 39" src="https://user-images.githubusercontent.com/31047486/34330930-f8d53756-e8d6-11e7-8e4d-77b26a2d27df.png">

Pongamos esto como prioridad!

**Comment by cjairm** [comment]
@DavelBM  checked
